### ISSUE TITLE
TypeError: format_data() missing 2 required positional arguments: 'outputFile' and 'name'

### ISSUE THREAD

**Issue by azmiara** [parandea17/Fruit-Classification#1]
Hello,
The code runs for a while and throws this error.
```
Traceback (most recent call last):
  File "/home/azmi/projects/Fruit-Classification-master/classifier.py", line 161, in <module>
    run_training(89, 0.001, 40, 13)
  File "/home/azmi/projects/Fruit-Classification-master/classifier.py", line 152, in run_training
    test_data = dataset.get_test_data(batch_size)
  File "/home/azmi/projects/Fruit-Classification-master/dataset.py", line 70, in get_test_data
    test_images, test_labels = format_data(data)
TypeError: format_data() missing 2 required positional arguments: 'outputFile' and 'name'
```
I see that in the get_test_data() function you have mentioned "test_images, test_labels = **format_data(data)**" but format_data() takes three arguements.
PLease let me know how to correct this error.

**Comment by aparande** [comment]
Hello,

Please try replacing the get_test_date() function with the following:

```
def get_test_data(batch_size):
    try:
        test_file = h5.File(TEST_DIR+'fruit_data.hdf5', 'r')
        return test_file["Test"]["images"], test_file["Test"]["labels"]
    except:
        print("Constructing test data from scratch")
        data = []
        for subdir, dirs, files in os.walk(TEST_DIR):
            for file in files:
                label = os.path.basename(subdir)
                if label in CLASSES:
                    path = os.path.join(subdir, file)
                    data.append((image_to_array(path), get_label(label)))

        test_file = h5.File(TEST_DIR+'fruit_data.hdf5', 'w')
        test_images, test_labels = format_data(data, test_file, "Test")
        iteration = 1
        while batch_size * iteration < len(data):
            iteration += 1

        return test_images[:batch_size * (iteration - 1)], test_labels[:batch_size * (iteration - 1)]
```
